# Generated by Django 6.0 on 2025-12-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=40)),
                ('admin_email', models.CharField(max_length=60)),
                ('admin_password', models.CharField(max_length=15)),
            ],
        ),
    ]
