# Generated by Django 6.0 on 2025-12-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=70)),
                ('user_photo', models.FileField(upload_to='Assets/user/')),
                ('user_password', models.CharField(max_length=15)),
            ],
        ),
    ]
