# Generated by Django 6.0 on 2025-12-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
    ]
