# Generated by Django 6.0 on 2025-12-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_tbl_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.DeleteModel(
            name='tbl_brand',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.DeleteModel(
            name='tbl_type',
        ),
        migrations.DeleteModel(
            name='tbl_user',
        ),
        migrations.DeleteModel(
            name='tbl_category',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
