# Generated by Django 6.0 on 2025-12-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0009_delete_tbl_admin_delete_tbl_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=40)),
                ('admin_email', models.CharField(max_length=60)),
                ('admin_password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=40)),
                ('instructor_email', models.CharField(max_length=90)),
                ('instructor_password', models.CharField(max_length=10)),
                ('instructor_contact', models.CharField(max_length=10)),
                ('instructor_headline', models.CharField(max_length=40)),
                ('instructor_photo', models.FileField(upload_to='Assets/user/')),
                ('instructor_biography', models.CharField(max_length=900)),
                ('instructor_Qualification', models.CharField(max_length=400)),
                ('instructor_field', models.CharField(max_length=40)),
                ('instructor_proof', models.FileField(upload_to='Assets/user/')),
                ('instructor_securityQuestion', models.CharField(max_length=100)),
                ('instructor_securityAnswer', models.CharField(max_length=100)),
                ('instructor_gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=30)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_headline', models.CharField(max_length=70)),
                ('user_biography', models.CharField(max_length=900)),
                ('user_photo', models.FileField(upload_to='Assets/user/')),
                ('user_password', models.CharField(max_length=15)),
                ('user_securityQuestion', models.CharField(max_length=100)),
                ('user_securityAnswer', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_category')),
            ],
        ),
    ]
