# Generated by Django 6.0 on 2025-12-27 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=40)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=60)),
                ('course_desc', models.CharField(max_length=100)),
                ('course_date', models.CharField(max_length=40)),
                ('course_price', models.CharField(max_length=100)),
                ('course_image', models.FileField(upload_to='Assets/user/')),
                ('course_average', models.CharField(max_length=100)),
                ('course_requerements', models.CharField(max_length=100)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_instructor')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_topic')),
            ],
        ),
    ]
