# Generated by Django 6.0 on 2025-12-27 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_tbl_topic_tbl_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_purchasecourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=80)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_course')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_title', models.CharField(max_length=80)),
                ('material_desc', models.CharField(max_length=100)),
                ('material_file', models.FileField(upload_to='Assets/user/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_section')),
            ],
        ),
    ]
