# Generated by Django 6.0 on 2025-12-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_tbl_purchasecourse_tbl_section_tbl_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_issuedate', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=100)),
                ('chat_date', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=300)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_issuetype', models.CharField(max_length=100)),
                ('report_issuedesc', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
