# Generated by Django 6.0 on 2026-01-27 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_tbl_cart_tbl_links_tbl_progress_tbl_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaent_title', models.CharField(max_length=300)),
                ('complaent_content', models.CharField(max_length=300)),
                ('complaent_date', models.CharField(max_length=70)),
                ('complaent_reply', models.CharField(max_length=300, null=True)),
                ('complaent_status', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=300)),
                ('feedback_date', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
