# Generated by Django 6.0.2 on 2026-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_tbl_complaent_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_instructor',
            name='instructor_status',
            field=models.IntegerField(default=0),
        ),
    ]
