# Generated by Django 6.0.2 on 2026-02-03 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_tbl_instructor_instructor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_course',
            name='course_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
